# Generated by Django 4.2.3 on 2023-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="web_page", name="urls", field=models.URLField(),
        ),
    ]
