# Generated by Django 4.2.3 on 2023-08-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_acess_record_date"),
    ]

    operations = [
        migrations.RenameField(model_name="web_page", old_name="urls", new_name="url",),
    ]
