# Generated by Django 4.2.3 on 2023-08-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_urls_web_page_url"),
    ]

    operations = [
        migrations.RenameModel(old_name="Acess_record", new_name="Accessrecord",),
    ]
